from flask import Flask, render_template, request, jsonify
import webbrowser
import urllib.parse

app = Flask(__name__)

"""
WhatsApp Sharing Feature:
- Automatically opens WhatsApp Web with a pre-formatted message
- Lists all safe places with their categories, distances, and Google Maps links
- Users can share the message with any contact or group
- No phone number required - user selects recipient in WhatsApp
- Uses direct URL approach (no automation libraries needed)
"""

@app.route('/')
def home():
    # In a real app, you might pass API keys or config here
    return render_template('index.html')

@app.route('/navigation')
def navigation():
    return render_template('navigation.html')

@app.route('/share-whatsapp', methods=['POST'])
def share_whatsapp():
    try:
        data = request.json
        phone = data.get('phone', '')
        places = data.get('places', [])
        location_name = data.get('location', 'Unknown Location')
        
        # Format message
        message = f"🆘 *HILL-SAFE Emergency Alert* 🆘\n\n"
        message += f"📍 *Safe Places Near: {location_name}*\n"
        message += f"⏱️ All locations within 20-min walking distance\n\n"
        
        if places:
            message += f"🏆 *Top {len(places)} Safe Locations:*\n\n"
            for i, place in enumerate(places, 1):
                name = place.get('name', 'Unknown')
                category = place.get('category', 'Building')
                distance = place.get('distance', 'N/A')
                lat = place.get('lat', 0)
                lon = place.get('lon', 0)
                
                # Add emoji based on category
                emoji = '🏥' if 'Hospital' in category else '🏠' if 'Shelter' in category else '⛰️' if 'High Ground' in category else '🏢'
                
                message += f"{i}. {emoji} *{name}*\n"
                message += f"   📂 {category}\n"
                message += f"   📏 {distance} away\n"
                message += f"   🗺️ https://www.google.com/maps/dir/?api=1&destination={lat},{lon}\n\n"
        else:
            message += "⚠️ No safe places found in this area.\n\n"
        
        message += "\n🔗 Generated by Hill-Safe App"
        message += "\n⚠️ Stay Safe! Share with your family and friends."
        
        return jsonify({
            'success': True,
            'message': 'WhatsApp ready to open!',
            'preview': message
        })
    
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

if __name__ == '__main__':
    app.run(debug=True, port=5000)